- name: Install AWS CLI
  apt:
    name: awscli
    state: present
    update_cache: yes

- name: Configure AWS credentials
  copy:
    dest: "/home/ubuntu/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ aws_access_key }}
      aws_secret_access_key = {{ aws_secret_key }}
      region = {{ aws_region }}
    owner: ubuntu
    mode: '0600'
