services:
  ad-nginx:
    container_name: ad-nginx
    image: nginx:alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    networks:
      - ad-network

  ad-certbot:
    container_name: ad-certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    # 1. Comment out the ssl server block
    # 2. run docker-compose run --rm ad-certbot certonly --webroot --webroot-path /var/www/certbot/ --email ${EMAIL} --agree-tos --no-eff-email  -d ${DOMAIN} -d www.${DOMAIN}
    # 3. Uncomment the ssl server block
    # 4. restart nginx `docker compose exec ad-nginx nginx -s reload`

networks:
  ad-network:
    driver: bridge
