services:
  ad-nginx:
    container_name: ad-nginx
    depends_on:
      - ad-certbot
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - ad-network

  ad-certbot:
    container_name: ad-certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./:/serverSetup
    command:
      certonly --webroot --webroot-path=/serverSetup --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN} -d www.${DOMAIN}

      # to check that this worked, run the following command
      # docker-compose exec ad-nginx ls -la /etc/letsencrypt/live
      # look for a file with the domain name `andydelgado.dev`
      # then, change --staging for --force-renewal

volumes:
  certbot-etc:

networks:
  ad-network:
    driver: bridge
