version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:

      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yoursecurepassword
      - WEBHOOK_TUNNEL_URL=https://yourdomain.com
      - GENERIC_TIMEZONE=America/New_York

