- name: Ensure required dependencies are installed
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes

- name: Download AWS CLI installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Install AWS CLI
  command: "/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update"
  become: yes

- name: Remove AWS CLI installation files
  file:
    path: "/tmp/awscliv2.zip"
    state: absent

- name: Remove AWS CLI extracted directory
  file:
    path: "/tmp/aws"
    state: absent

- name: Verify AWS CLI installation
  command: "aws --version"
  register: aws_cli_version
  changed_when: false

- name: Debug AWS CLI version
  debug:
    msg: "Installed AWS CLI version: {{ aws_cli_version.stdout }}"
