- name: Ensure required dependencies are installed
  become: yes
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  tags:
    - aws_cli

- name: Download AWS CLI installer
  become: yes
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'
  tags:
    - aws_cli

- name: Unzip AWS CLI installer
  become: yes
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes
  tags:
    - aws_cli

- name: Install AWS CLI
  become: yes
  command: "/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update"
  become: yes

- name: Remove AWS CLI installation files
  become: yes
  file:
    path: "/tmp/awscliv2.zip"
    state: absent
  tags:
    - aws_cli

- name: Remove AWS CLI extracted directory
  become: yes
  file:
    path: "/tmp/aws"
    state: absent
  tags:
    - aws_cli

- name: Verify AWS CLI installation
  become: yes
  command: "aws --version"
  register: aws_cli_version
  changed_when: false
  tags:
    - aws_cli

- name: Debug AWS CLI version
  become: yes
  debug:
    msg: "Installed AWS CLI version: {{ aws_cli_version.stdout }}"
  tags:
    - aws_cli
