- name: Ensure dependencies are installed
  apt:
    name: [curl, tar]
    state: present
  become: yes
  tags:
    - github_actions

- name: Create runner directory
  file:
    path: '{{ runner_dir }}'
    state: directory
    mode: '0755'
  tags:
    - github_actions

- name: Download GitHub runner tarball
  get_url:
    url: '{{ runner_url }}'
    dest: '{{ runner_dir }}/actions-runner.tar.gz'
    mode: '0644'
  tags:
    - github_actions

- name: Extract runner tarball
  unarchive:
    src: '{{ runner_dir }}/actions-runner.tar.gz'
    dest: '{{ runner_dir }}'
    remote_src: yes
  tags:
    - github_actions

- name: Configure the GitHub runner
  command: './config.sh --url {{ repo_url }} --token {{ runner_token }} --unattended'
  args:
    chdir: '{{ runner_dir }}'
  environment:
    RUNNER_ALLOW_RUNASROOT: '1'
  tags:
    - github_actions

- name: Install GitHub runner service
  command: './svc.sh install'
  args:
    chdir: '{{ runner_dir }}'
  tags:
    - github_actions

- name: Start GitHub runner service

  command: './svc.sh start'
  args:
    chdir: '{{ runner_dir }}'
  tags:
    - github_actions
