- name: Get Recommended Nginx Security Parameter
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: ../configs/nginx/options-ssl-nginx.conf
    mode: 644
  tags:
    - nginx
