- name: Decrypt stuff
  copy:
    src: '../.stuff'
    dest: '../.s'
    mode: 0644
    owner: '{{ user }}'
  tags:
    - setup

- name: Get Recommended Nginx Security Parameter
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: ../configs/nginx/options-ssl-nginx.conf
    mode: 644
  tags:
    - setup

- name: Install fail2ban
  become: true
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present
    update_cache: true
  tags:
    - setup

- name: Install fail2ban config file
  become: true
  ansible.builtin.copy:
    src: '{{ home }}/serverSetup/configs/fail2ban.conf'
    dest: '/etc/fail2ban/fail2ban.conf'
    mode: 0775
    owner: '{{ user }}'
  tags:
    - setup

- name: Install jail config file
  become: true
  ansible.builtin.copy:
    src: '{{ home }}/serverSetup/configs/jail.conf'
    dest: '/etc/fail2ban/jail.conf'
    mode: 0775
    owner: '{{ user }}'
  tags:
    - setup

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: fail2ban
  tags:
    - setup

- name: Install sshd config file
  become: true
  ansible.builtin.copy:
    src: '{{ home }}/serverSetup/configs/sshd_config'
    dest: '/etc/ssh/sshd_config'
    mode: 0775
  owner: '{{ user }}'
  tags:
    - setup

- name: Restart sshd
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: sshd
  tags:
    - setup

- name: Install nodejs and npm - Debian
  become: true
  ansible.builtin.apt:
    name: ['nodejs', 'npm']
  tags:
    - setup
    - node

- name: Create npmjs prefix folder if it doesn't exist
  ansible.builtin.file:
    path: '{{ home }}/.local/.npm-global'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - setup
    - node

- name: Npmjs global settings
  ansible.builtin.command: npm config set prefix '{{ home }}/.local/.npm-global'
  tags:
    - setup
    - node

- name: Install N interactive node manager
  npm:
    name: n
    global: true
  tags:
    - setup
    - node

# N needs to write to /usr/local
# to avoid sudo, we can own the folder
- name: Create folder for n if it doesn't exist
  become: true
  ansible.builtin.file:
    path: '/usr/local/n/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - setup
    - node

- name: Install node version specified in ../local.yml
  become: true
  ansible.builtin.shell: '{{ home }}/.local/.npm-global/bin/n {{ node_version }}'
  tags:
    - setup
    - node

- name: Install pm2
  npm:
    name: pm2
    global: true
  tags:
    - setup
    - npm-packages

- name: pm2 update
  become: true
  ansible.builtin.command: pm2 update
  tags:
    - setup
    - npm-packages

- name: pm2 completion install
  become: true
  ansible.builtin.command: pm2 completion install
  tags:
    - setup
    - npm-packages
