- name: Install sshd config file
  become: true
  ansible.builtin.copy:
    src: '{{ home }}/serverSetup/configs/sshd_config'
    dest: '/etc/ssh/sshd_config'
    mode: 0775
    owner: '{{ user }}'
  tags:
    - sshd

- name: Restart sshd
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: ssh
  tags:
    - sshd

